export const apiRoutes = {
  Login: "api/user/github/login",
  Profile: "api/user/detail",
  Logout: "api/user/logout",
  AllApp: "api/apps/list",
  AddApp: "api/apps/create",
  Release: "api/releases",
  Environments: "api/apps/environments",
  AddEnv: "api/apps/environments",
  DeleteApp: "api/apps/delete",
  DeleteCollab: "api/collaborators/invitation",
  UpdateApp: "api/apps/edit",
  AppDetail: "api/apps/details",
  Collaborators: "api/collaborators",
  SendInvite: "api/collaborators/send-invite",
  CheckInvite: "api/collaborators/check-invitation",
  AcceptInvite: "api/collaborators/accept-invitation",
  RollBack: "api/releases/rollback",
  Promote: "api/releases/promote",
  Rollout: "api/releases/rollout",
  ReleaseDetail: "api/releases",
  UploadLogo: "car-wash/v1/upload/app-icon",
};
