name: lower code push web deploymnet 

on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Which Environment to deploy to ?'
        required: true
        type: choice
        options:
          - DEV

        default: 'DEV'
env:
  DEV_ENV: ${{ secrets.DEV_ENV }}
  
jobs:
  build_and_deploy_to_storage_account:
    runs-on: lower-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 22
        

      - name: Get DEV env file
        if:  ${{ inputs.environment == 'DEV' }}      
        run: |
          touch .env
          echo "Storing DEV_ENV into env.txt"
          echo ${{ env.DEV_ENV }} > env.txt
          echo "Decoding env.txt and storing it in .env file"
          base64 --decode env.txt > .env
          cat .env
          ls -la
          pwd
        
      - name: Code build   
        run: |
          npm install
          npm run build
          ls -la
       

      # Azure login via Managed Identity
      - name: Azure login via Managed Identity
        run: |
          az login --identity      

      - name: Deploy to DEV blob storage
        if:  ${{ inputs.environment == 'DEV' }}
        run: |
          ls -la
          echo "Starting Code Deployment..."
          az storage blob upload-batch --account-name skipstorecodepushweb --auth-mode login --overwrite -d '$web' -s dist/
          echo "Code Has Been Deployed"

      - name: Purge DEV AFD endpoint
        if:  ${{ inputs.environment == 'DEV' }}      
        run: |
          echo "Purging AFD Endpoint..."
          az afd endpoint purge --resource-group son_eastus2_ctl_skipstore_rg04 --profile-name skipstorefd-preprod --endpoint-name skipstore-codepush --domains skipstore-codepush-dec8c2a4cyabbxf2.z03.azurefd.net --content-paths '/*'          
          echo "AFD enpoint has been purged..."           

          

      - name: azure logut 
        run: |
          az logout
